enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/logo.png:
    name: logo.png
    full_path: logo.png
    type: image/png
    size: 8501
    path: user/themes/quark/images/logo/logo.png
custom_logo_mobile: {  }
footer_location_link: null
Contact_address: 'Warehouse No.15, Street 24, Al Quoz industrial area - 4'
Phone_number: '+971 52 240 55 44'
Whatsapp_number: '+971 52 240 55 44'
Email: info@royalpool.com
facebook_link: 'https://facebook.com'
twitter_link: 'https://x.com'
youtube_link: 'https://youtube.com'
instagram_link: 'https://instagram.com'
linkedin_link: 'https://linkedin.com'
brochure:
  user/themes/quark/media/broucher.pdf:
    name: broucher.pdf
    full_path: broucher.pdf
    type: application/pdf
    size: 12690738
    path: user/themes/quark/media/broucher.pdf
